### ISSUE TITLE
[Suggestion] localForage ?

### ISSUE THREAD

**Issue by darkyen** [jvilk/BrowserFS#126]
localForage is an excellent project by mozilla, it shims the indexedDB and WebSQL and ofcourse localStorage under a single localStorage like api, which is pretty neat !

**Comment by jvilk** [comment]
I'm aware of the project. What is your suggestion? BrowserFS supports both IndexedDB and localStorage as file system backends, which can be composed with other BrowserFS file systems (e.g. MountableFileSystem, OverlayFS, etc). I haven't added WebSQL support since it's dying, but that can be implemented as a backend if desired.

**Comment by jvilk** [comment]
I'm closing this for now, as I'm not sure what your suggestion or question is. Feel free to reopen! :)
