### ISSUE TITLE
Question: What does wrapCB do?

### ISSUE THREAD

**Issue by hrj** [jvilk/BrowserFS#138]
While analysing the heap in Firefox, I noticed a large number of allocations in https://github.com/jvilk/BrowserFS/blob/279eaa0e278f6135c3ddfac69064d1c23cba45ce/src/core/FS.ts#L19

What is the purpose of wrapCB? Is it to yield more often to the main thread? If so, wouldn't it be better to let the caller do the yielding themselves in their callback function?

**Comment by jvilk** [comment]
We use it for unit tests. It lets the unit test runner know when all callbacks have run, since they are adapted from Node and that is their end condition.

That's it.

I never added logic to remove or disable it in "production" builds, as it was never a bottleneck and would not have been worth the engineering time. I will happily accept a pull request that makes it toggle-able.

**Comment by hrj** [comment]
Cool; thanks.

After removing the wrapping, I didn't find any performance impact either, but maybe it does on memory constrained systems.

I am raising a PR, but there is some build failure in bfs-buffer, which I don't know what to do about.
