### ISSUE TITLE
IE8/9 compatiblity?

### ISSUE THREAD

**Issue by hrj** [jvilk/BrowserFS#159]
The switch to typed arrays is exciting; looking forward to improved performance.

However, did the release 1.0.0 drop IE8 / 9 compatibility? Or was it dropped in 0.6.0 as alluded in the [release notes for 0.5.13](https://github.com/jvilk/BrowserFS/releases/tag/v0.5.13)?

**Comment by jvilk** [comment]
@hrj IE8 is no longer supported in 1.0.0 since I removed the polyfills in index.ts. IE9 may work in 1.0.0, but is untested and unsupported.

0.6.1 works in IE9, and was tested in IE10 in IE9 mode on appveyor. It should work in IE8, too, but I do not believe it was tested in IE8.

Do you believe this is a problem? Previously, BrowserFS was broken in IE8/9 before I added official regression testing, and nobody complained.

**Comment by jvilk** [comment]
I clarified the release notes.

**Comment by hrj** [comment]
Not really a problem; never used IE8/9 myself or heard any complaints :)

Just wanted to document it in my code before updating to the latest version of BFS.

**Comment by jvilk** [comment]
Gotcha. Thanks for checking! The release notes are now clearer.

**Comment by hrj** [comment]
Thanks!

BTW, are you planning to update doppio to the newer BFS anytime soon? If not I could give it a shot.

**Comment by jvilk** [comment]
@hrj I have it working in a local branch. I did not push it yet, since I decided to do the small bug fix first before ripping off the compatibility bandaid in a major release. Then, I got distracted!

I'll push it tonight or over the weekend.

**Comment by hrj** [comment]
@jvilk Awesome; eagerly awaiting.
