### ISSUE TITLE
Consider developing with --strictNullChecks enabled?

### ISSUE THREAD

**Issue by bolinfest** [jvilk/BrowserFS#164]
I just ran `./node_modules/.bin/tsc -p src --strictNullChecks`, and it surfaced 322 diagnostics. It would be nice to tighten this up.

Or just use [Flow](https://flowtype.org/) where this is the default behavior :)

**Comment by jvilk** [comment]
I haven't enabled this option because it seemed like excessive effort for relatively little benefit. Most BFS bugs are logic errors rather than null dereferences.

If this is something you're interested in, though, I will accept PRs that enable the option and fixes the error messages so long as the changes do not noticeably impact performance.

Switching the library to another programming language, though, is out of the question. :)

**Comment by jvilk** [comment]
Done.
