### ISSUE TITLE
new BrowserFS.FileSystem.InMemory() fails in PhantomJS

### ISSUE THREAD

**Issue by hitsthings** [jvilk/BrowserFS#175]
PhantomJS doesn't support ArrayBuffer.isView(). As part of makeRootDirectory(), a new Buffer is created with new Buffer("{}") which in turn calls ArrayBuffer.isView("{}") and throws.

Cross-reference in PhantomJS repo - https://github.com/ariya/phantomjs/issues/14868

This is causing an archiving issue for the Internet Archive iiuc - https://twitter.com/textfiles/status/838185877067071488

**Comment by jvilk** [comment]
[The Buffer module we use](https://github.com/feross/buffer) requires a functioning Typed Array implementation. 

As an aside, I no longer test against PhantomJS [because its web worker implementation is completely broken](https://github.com/jvilk/BrowserFS/issues/122). It seems pretty bad that PhantomJS needs to re-implement core browser features that are already present in WebKit/V8. I don't think I can be responsible for working around all of those problems.

[SlimerJS](https://slimerjs.org) is a great alternative to PhantomJS and (AFAIK) presents a PhantomJS-compatible API. It commands a specific, unmodified version of Firefox, so any webpage that works in Firefox will work in Slimer.

Here's an untested hackfix that you could drop in to a webpage using BrowserFS to work around this bug. It seems to work on a few test objects I threw at it, but I cannot claim that it is foolproof:

```javascript
if (!ArrayBuffer.isView) {
  // PhantomJS has an incomplete implementation of ArrayBuffers, and does not implement isView.
  ArrayBuffer.isView = function(o) {
    return typeof(o) === "object" && o.buffer instanceof ArrayBuffer;
  };
}
```

Note that this hackfix does not work on ArrayBuffers transferred between contexts (like iframes) for the same reason why you cannot reliably use `[] instanceof Array` and must use `Array.isArray` instead. For the Internet Archive, though, it should be good enough.

I hope this helps!

**Comment by hitsthings** [comment]
Thanks a ton! Fair enough not supporting it. Dunno what they have planned
but I agree it probably makes sense to move away from phantom.

**Comment by jvilk** [comment]
Oh, @hitsthings, if you use that polyfill, you should add a null check to avoid a null dereference:

```javascript
if (!ArrayBuffer.isView) {
  // PhantomJS has an incomplete implementation of ArrayBuffers, and does not implement isView.
  ArrayBuffer.isView = function(o) {
    return o && typeof(o) === "object" && o.buffer instanceof ArrayBuffer;
  };
}
```

(`typeof(null)` is `"object"` :| )
