### ISSUE TITLE
Publish version 2.0.0 to npm already?

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#209]
:)

**Comment by jvilk** [comment]
I had some plans to do a few more breaking changes, since it's a big version bump, but have had some things come up that are currently consuming all of my free time.

Would it help to push a 2.0 beta in the mean time? If I don't find the time to start making the changes I want within the next month, then I can make it final and make subsequent changes in a 3.0. (I just hate to impose churn on folks.)

**Comment by wmhilton** [comment]
A prerelease tag / beta would be fine. Anything so I can use it in devDependencies instead of bundling it myself and including the minified version in my own package. (I tried using a github url in package.json but it didn't work.) I guess I could publish a scoped fork... but yeah if you could publish a 2.0.0-alpha.1 that would be peachy.

**Comment by wmhilton** [comment]
Because the 1.x branch doesn't have global.fetch (and therefore ServiceWorker) support IIRC.

**Comment by jvilk** [comment]
"Publish a beta" is on my TODO list for today. Thanks for your patience; I've had many other things on my plate lately!

**Comment by jvilk** [comment]
I just published v2.0.0 to the beta channel, and uploaded API docs for 2.0.0. I'll try to get together a roadmap for 2.0.0 so we can get this stable, too.
