### ISSUE TITLE
FS createReadStream not supported?

### ISSUE THREAD

**Issue by nicmosc** [jvilk/BrowserFS#217]
I can't seem to get the `createReadStream` function to work and I'm getting a ENOTSUP error. I assume it's because this method hasn't been implemented?

I would need this to stream the files to an S3 uploader (not from the official aws sdk). If streams are not yet supported how would I go about doing something like this? Reading from the dir with the s3 client fails as they have their own custom fs dependency.

**Comment by jvilk** [comment]
`createReadStream` is on the roadmap for the next major release, and I don't have an ETA for it due to other commitments.

You could consider writing a simple polyfill for your current needs, e.g. that uses `readFile` to read a file into a buffer, pushes it into a NodeJS readable stream, and ends the stream. Just overwrite the supplied stub that throws `ENOTSUP` with that code.

**Comment by rektide** [comment]
Duplicate of #124.
