### ISSUE TITLE
"Error: undefined: XHR error." when running on file://

### ISSUE THREAD

**Issue by 1j01** [jvilk/BrowserFS#220]
It fails because it gets a status of 0 and decides that's a failure, even tho the response data is there.

That is not a pretty error message:
![not a pretty error message](https://user-images.githubusercontent.com/3630663/38124417-83a0ad7a-33af-11e8-85da-9d9754141371.png)

Now, if there are reasons for this to not be supported (using `--allow-file-access-from-files` for chrome), the error could at least say something about that; but I can't think of why it shouldn't be able to work.

**Comment by jvilk** [comment]
Agreed that the error message could be better, but this is a project maintained by one person in his spare time. I assumed that the status would be 200 on a success, and didn't think about accessing file:// URLs where HTTP status codes don't apply.

Seems like an easy fix. I'll happily accept a PR, otherwise I'll try to get to this soon.

**Comment by dr-vortex** [comment]
Closing since BrowserFS has stopped using XHR.
