### ISSUE TITLE
Create a new release 

### ISSUE THREAD

**Issue by AntonOfTheWoods** [jvilk/BrowserFS#362]
The build system currently has some issues and it requires quite a lot of effort to understand what is going on. Many years appear to have passed since a new version has been released, and many features and bugs are missing in the npm version. Could a beta2 be released to ease these pain points?

**Comment by dr-vortex** [comment]
I'm working on getting NPM publish permissions from jvilk but he is very busy IRL so that is taking a while.

**Comment by AntonOfTheWoods** [comment]
@dr-vortex you closed this because it was annoying you rather than because a release was made?

**Comment by dr-vortex** [comment]
@AntonOfTheWoods No. I closed this because while I would love to create a new release, I don't have the permissions. The purpose of issues (in my opinion) are to bring up questions and concerns of any kind that should be addressed. I guarantee the second I have permissions, a new beta will be released (provided CI checks are successful). Hence, there is not a reason for the issue to remain open.

**Comment by AntonOfTheWoods** [comment]
Sure. I agree there are lots of project maintainers who have that view of issues, and the maintainer makes the rules. Personally, I prefer the view that issues function as points of contact for active issues that users/Devs encounter with the codebase. Until the issue is resolved, a ticket stays open so others don't create new issues needlessly, and can quickly see what is ongoing (and they might lend a hand...). A wontfix is definitely also a resolution, of course! But plenty of maintainers don't agree with me, so I'll not bother you further!

**Comment by dr-vortex** [comment]
@AntonOfTheWoods I 100% agree with you. Feel free to re-open the issue if you want. I'm doing everything I can to get a release out but @jvilk is *very* busy and I need him to give me permissions on NPM.
