### ISSUE TITLE
Web Workers

### ISSUE THREAD

**Issue by SpiritedDusty** [jvilk/BrowserFS#89]
Is there a way I could use BrowserFS's localStorage backend while being in a web worker? Since web workers don't have access to localStorage, I don't expect BrowserFS to work in a web worker with the localStorage backend.

**Comment by jvilk** [comment]
I just added WorkerFS to BrowserFS, which lets you mount file systems from the main thread in a web worker (and visa-versa). This will enable you to write files to localStorage from a Web Worker, but since WebWorker communications are asynchronous, you cannot integrate this into the Emscripten file system.

I will open an issue for a "AsyncSync" file system wrapper, which will load the entire contents of an asynchronous file system into a synchronous file system at bootup, and will sync writes asynchronously to the backing storage as they occur. This will let Emscripten mount *any* asynchronous storage.

**Comment by jvilk** [comment]
This isn't in the latest BFS release, btw. But it will be in the next one, which should occur today or tomorrow.
